Repository SB2318/UltimateHealth, pull requests merged in 2024-06, with the labels that each got.

#99 Create API for Storing Doctor Specializations.
  backend/controllers/specializationsControllers.js
  backend/models/SpecializationsModel.js
  backend/routes/SpecializationsRoutes.js
  backend/server.js
Labels: enhancement, gssoc, level3

#104 Delete user account from backend issue ID : #97
  backend/.env
  backend/auth/authMiddleware.js
  backend/controllers/usersControllers.js
  backend/models/adminModel.js
  backend/package-lock.json
  backend/routes/usersRoutes.js
  backend/server.js
  frontend/package-lock.json
Labels: enhancement, gssoc, level3

#111 Updated readme.md ( Added Contributor Code History, Tech Stack Logos, Number of Forks, Number of PRs, Last Commit)
  README.md
Labels: good first issue, gssoc, level1

#112 Added Links to the Headings
  README.md
Labels: good first issue, gssoc, level1

#108 Designed Signup Module
  frontend/package-lock.json
  frontend/package.json
  frontend/src/navigations/StackNavigation.js
  frontend/src/screens/HomeScreen.tsx
  frontend/src/screens/auth/SignUpScreenFirst.tsx
  frontend/src/screens/auth/SignUpScreenSecond.tsx
Labels: enhancement, gssoc, level3

#110 [FEATURE]: Design Forgot Password module added
  frontend/package-lock.json
  frontend/src/assets/mail.png
  frontend/src/components/EmailInputModal.tsx
  frontend/src/navigations/StackNavigation.tsx
  frontend/src/screens/auth/LoginScreen.tsx
  frontend/src/screens/auth/NewPasswordScreen.tsx
  frontend/src/screens/auth/OtpScreen.tsx
Labels: gssoc, level2

#119 💡[FEATURE]: Add a show-hide feature for the password field in a login page #77
  frontend/src/screens/auth/LoginScreen.tsx
Labels: good first issue, gssoc, level1

#131 [FEATURE]: Create Tags or Article Categories API. #125
  backend/controllers/ArticleTagController.js
  backend/models/ArticleTagModel.js
  backend/routes/articleRoutes.js
  backend/server.js
Labels: good first issue, gssoc, level3

#133 Design HomeScreen
  frontend/App.tsx
  frontend/android/build.gradle
  frontend/babel.config.js
  frontend/ios/Podfile.lock
  frontend/ios/UltimateHealth.xcodeproj/project.pbxproj
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/ArticleCard.tsx
  frontend/src/screens/HomeScreen.tsx
Labels: gssoc, level3, article

#139 Updated Branch and completed all tasks for Login page Development #85
  backend/.env
  backend/controllers/articleController.js
  backend/models/ArticleModel.js
  backend/routes/articleRoutes.js
  backend/server.js
  frontend/App.tsx
  frontend/android/build.gradle
  frontend/babel.config.js
  frontend/index.js
  frontend/ios/Podfile.lock
  frontend/ios/UltimateHealth.xcodeproj/project.pbxproj
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/mail.png
  frontend/src/components/ArticleCard.tsx
  frontend/src/components/EmailInputModal.tsx
  frontend/src/helper/APIUtils.ts
  frontend/src/models/BaseObject.ts
  frontend/src/models/User.ts
  frontend/src/navigations/StackNavigation.tsx
  frontend/src/screens/HomeScreen.tsx
  frontend/src/screens/auth/LoginScreen.tsx
  frontend/src/screens/auth/NewPasswordScreen.tsx
  frontend/src/screens/auth/OtpScreen.tsx
  frontend/src/screens/auth/SignUpScreenFirst.tsx
  frontend/src/screens/auth/SignUpScreenSecond.tsx
  frontend/src/services/AuthApiService.ts
  frontend/src/store/NetworkSlice.ts
  frontend/src/store/ReduxStore.ts
  frontend/src/store/UserSlice.ts
Labels: enhancement

#138 💡[Feature]: Redirect User to home page After Verification Analysis and Possibility measurement. #134
  backend/auth/authMiddleware.js
  backend/controllers/emailservice.js
  backend/controllers/usersControllers.js
  backend/models/UnverifiedUserModel.js
  backend/models/UserModel.js
  backend/routes/usersRoutes.js
Labels: enhancement, gssoc, level3

#132 Added No Internet Layout
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/cloud-thunder-icon.png
  frontend/src/assets/no-internet-icon.png
  frontend/src/components/NoInternet.tsx
  frontend/src/helper/Utils.ts
  frontend/src/screens/HomeScreen.tsx
Labels: good first issue, gssoc, level2, in-progress

#129 Updated Readme.md #90
  README.md
Labels: good first issue, gssoc, level2
