Repository SB2318/UltimateHealth, pull requests merged in 2024-08, with the labels that each got.

#295 Added Are People Truly Possessed by Ghosts.md
  DataSources/Are People Truly Possessed by Ghosts.md
Labels: good first issue, gssoc, level3

#300 Understanding Allergies and How to Manage Them ( English & Hindi )
  DataSources/English/Understanding-Allergies-and-How-to-Manage-Them.md
  DataSources/Hindi/Understanding_Allergies_and_How_to_Manage_Them_Hindi.md
Labels: good first issue, gssoc, level3

#278 Health Myths Debunked: What You Thought You Knew
  DataSources/Health Myths Debunked.md
Labels: good first issue, gssoc, level3

#279 Role of Humor and Laughter in Wellness in (English & Hindi)
  DataSources/Humor and Laughter - Hindi.md
  DataSources/Humor and Laughter - english.md
Labels: good first issue, gssoc, level3

#281 The Intersection of Fitness and Technology: Trends to Watch (English & Hindi)
  DataSources/Fitness and Technology - Hindi.md
  DataSources/Fitness and Technology - english.md
Labels: good first issue, gssoc, level3

#286 Impact of Air Quality on Health convert into all language.
  DataSources/Hindi/The Impact of Air Quality on Health Hindi.md
  DataSources/Malay/The Impact of Air Quality on Health Malay.md
  DataSources/Marathi/The Impact of Air Quality on Health Marathi.md
  DataSources/Spanish/The Impact of Air Quality on Health Spanish.md
  DataSources/Tamil/The Impact of Air Quality on Health Tamil.md
Labels: good first issue, gssoc, level2

#301 Created Digital-Detox:Balancing_Technology_and_Mental_Health.md
  DataSources/Assets/Digital-Detox:Balancing_Technology_and_Mental_Health.md
Labels: good first issue, gssoc, level3

#305 Filter Page Design In figma
  frontend/src/screens/ProfileEditScreen.tsx
Labels: enhancement, gssoc, level2

#306 Role of Diet in Managing Autoimmune Diseases into Another Language.
  DataSources/Bengali/Role of Diet-Bengali.md
  DataSources/Hindi/Role of Diet-Hindi.md
  DataSources/Malay/Role of Diet-Malay.md
  DataSources/Marathi/Role of Diet-Marathi.md
  DataSources/Spanish/Role of Diet-Spanish.md
  DataSources/Tamil/Role of Diet-Tamil.md
Labels: good first issue, gssoc, level3

#308 Side Effect of Chemotherapy Added
  DataSources/English/Side_Effects_of_Chemotheraphy.md
  DataSources/Hindi/Side_Effects_of_Chemotheraphy_Hindi.md
Labels: enhancement, gssoc, level3

#315 Added Gut-Brain Connection
  DataSources/Assets/Gut Brain Connection/Article-English.md
  DataSources/Assets/Gut Brain Connection/Article-Hindi.md
  DataSources/Assets/Gut Brain Connection/Assets/Brain.jpeg
  DataSources/Assets/Gut Brain Connection/Assets/Gut-brain.jpeg
  DataSources/Assets/Gut Brain Connection/Assets/Symtoms.jpeg
  DataSources/Assets/Gut Brain Connection/Assets/mental health.jpg
Labels: good first issue, gssoc, level3

#314 Create PCOD_Unplugged:Unlocking_the_Secrets_to_Wellness.md
  DataSources/Assets/Hindi_PCOD_Unplugged: Unlocking_the_Secrets _toWellness.md
  DataSources/Assets/PCOD_Unplugged:Unlocking_the_Secrets_to_Wellness.md
  Tamil_PCOD_Unplugged: Unlocking_the_Secrets _toWellness.md
Labels: good first issue, gssoc, level3

#319 Leukemia - Blood Cancer
  DataSources/Leukemia.md
Labels: enhancement, gssoc, level3

#320 Thyroid Disorders - Diagnosis and Management
  DataSources/Thyroid Disorders.md
Labels: good first issue, gssoc, level3

#322 Added gut health and its influence on well being
  DataSources/Assets/GutHealth.webp
  DataSources/gut health and its influence on well being.md
Labels: enhancement, good first issue, gssoc, level3

#328 Benefits of Intermittent Fasting
  DataSources/Fasting.md
Labels: good first issue, gssoc, level3

#321 HIV/AIDS
  DataSources/HIV.md
Labels: good first issue, gssoc, level3

#335 Mental Health Awareness and Stigma ( English, Hindi & Marathi )
  DataSources/English/Mental-Health-Awareness-and-Stigma.md
  DataSources/Hindi/Mental-Health-Awareness-and-Stigma-Hindi.md
  DataSources/Marathi/Mental-Health-Awareness-and-Stigma-Marathi.md
Labels: enhancement, gssoc, level3

#338 Sustainable Fitness: Eco-Friendly Exercise Practices in English and Hindi
  DataSources/Sustainable Fitness: Eco-Friendly Exercise Practices/English.md
  DataSources/Sustainable Fitness: Eco-Friendly Exercise Practices/Hindi.md
Labels: good first issue, gssoc, level3

#344 Myeloma English & Hindi
  DataSources/Myeloma - English.md
  DataSources/Myeloma - Hindi.md
Labels: enhancement, gssoc, level3

#345 Rheumatoid Arthritis English & Hindi
  DataSources/Rheumatoid Arthritis - English.md
  DataSources/Rheumatoid Arthritis - Hindi.md
Labels: good first issue, gssoc, level3

#334 Filter Page Implementaion in frontend
  frontend/App.tsx
  frontend/index.js
  frontend/ios/Podfile.lock
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/CategoriesFlatlistModal.tsx
  frontend/src/components/FilterModal.tsx
  frontend/src/components/HomeScreenHeader.tsx
  frontend/src/helper/Utils.ts
  frontend/src/navigations/TabBar.tsx
  frontend/src/screens/HomeScreen.tsx
Labels: enhancement, gssoc, level3

#350 Updated pr_greet.yml
  .github/workflows/pr_greet.yml
Labels: good first issue, gssoc, level2

#357 PR Title Checker added
  .github/pr-title-checker.json
  .github/workflows/pr-title-checker.yml
Labels: good first issue, gssoc, level2

#342 Hypertension: The silent Killer (Tamil & Malay, Spanish)
  DataSources/Hypertension : The Silent Killer - Malay.md
  DataSources/Hypertension : The Silent Killer - Tamil.md
  DataSources/Hypertension : The Silent Killer -Spanish.md
Labels: good first issue, gssoc, level3

#349 DIY Natural Remedies: Safe and Effective Homemade Solutions in English and Hindi
  DataSources/Natural Remedies - Hindi.md
  DataSources/Natural Remedies.md
Labels: good first issue, gssoc, level3

#360 Created Humor and Laughter - Spanish.md
  DataSources/Humor and Laughter - Spanish.md
Labels: good first issue, gssoc, level2

#347 Create Immuno-Boosting Trends: Enhancing Your Body’s Defense System.md
  DataSources/Assets/Immuno-Boosting Trends: Enhancing Your Body’s Defense System.md
Labels: good first issue, gssoc, level3

#351 Breathing Easy: Effective Asthma Management Strategies
  DataSources/Breathing Easy: Effective Asthma Management Strategies/English.md
  DataSources/Breathing Easy: Effective Asthma Management Strategies/Hindi.md
Labels: good first issue, gssoc, level3

#370 Updated pr_greet.yml
  .github/workflows/pr_greet.yml
Labels: enhancement

#364 Created auto-comment-pr-merge.yml
  .github/workflows/auto-comment-pr-merge.yml
Labels: enhancement, gssoc, level2

#361 Prostate Cancer - Awareness and Action
  DataSources/Prostate-Cancer-Awareness/English.md
  DataSources/Prostate-Cancer-Awareness/Hindi.md
Labels: good first issue, gssoc, level3

#367 Breast Cancer in English & Hindi
  DataSources/Breast Cancer - Hindi.md
  DataSources/Breast Cancer.md
Labels: good first issue, gssoc, level3

#371 Neuroplasticity.md
  DataSources/Neuroplasticity.md
Labels: enhancement, good first issue, gssoc, level3

#375 feat: added workflows: close old issues
  .github/workflows/close-old-issue.yml
  .github/workflows/close-old-pr.yml
Labels: good first issue, gssoc, level2

#378 Are People Truly Possessed by Ghosts (Hindi and Spanish)
  DataSources/Are People Truly Possessed by Ghosts? - Hindi.md
  DataSources/Are People Truly Possessed by Ghosts? - Spanish.md
Labels: good first issue, gssoc, level2

#382 Added "Parkinson's Pathway: Early Signs and Effective Treatments"
  DataSources/Parkinson's Pathway: Early Signs and Effective Treatments/English.md
  DataSources/Parkinson's Pathway: Early Signs and Effective Treatments/Hindi.md
Labels: enhancement, good first issue, gssoc, level3

#383 Added "Living with Hashimoto's: Practical Tips for Managing Symptoms"
  DataSources/Living with Hashimoto's: Practical Tips for Managing Symptoms/English.md
  DataSources/Living with Hashimoto's: Practical Tips for Managing Symptoms/Hindi.md
Labels: enhancement, good first issue, gssoc, level3

#392 Importance of skincare
  DataSources/Importance of Natural Skin Care with DIY Natural Remedies/Article-eng.md
  DataSources/Importance of Natural Skin Care with DIY Natural Remedies/Article-hindi.md
  DataSources/Importance of Natural Skin Care with DIY Natural Remedies/Assets/skin.jpeg
  DataSources/Importance of Natural Skin Care with DIY Natural Remedies/Assets/skincare benefits.jpeg
  DataSources/Importance of Natural Skin Care with DIY Natural Remedies/Assets/skincare.jpeg
Labels: good first issue, gssoc, level3

#355 Genetic Disorders and the incidence of genetic-based health disorders Added
  DataSources/Assets/image-1.png
  DataSources/Assets/image-2.png
  DataSources/Assets/image-3.png
  DataSources/Assets/image-4.png
  DataSources/Assets/image-5.png
  DataSources/Assets/image.png
  DataSources/English/Genetic-Disorders-English.md
Labels: good first issue, gssoc, level3

#395 Added "Tuberculosis Unveiled: The Evolution of Modern Treatments"
  Datasources/Tuberculosis Unveiled: The Evolution of Modern Treatments/English.md
  Datasources/Tuberculosis Unveiled: The Evolution of Modern Treatments/Hindi.md
Labels: good first issue, gssoc, level3

#400 The Science Behind Plant-Based Diets
  DataSources/English/Plant-based-diets.md
Labels: enhancement, gssoc, level3

#396 Stem cell therapy
  Datasources/stem cell therapy.md
Labels: enhancement, good first issue, gssoc, level3

#381 The-effects-of-loneliness
  DataSources/The-effects-of-loneliness-on-health-and-strategies-for-recovery/Article-english.md
  DataSources/The-effects-of-loneliness-on-health-and-strategies-for-recovery/Article-hindi.md
  DataSources/The-effects-of-loneliness-on-health-and-strategies-for-recovery/Assets/keylife.png
  DataSources/The-effects-of-loneliness-on-health-and-strategies-for-recovery/Assets/lone2.png
  DataSources/The-effects-of-loneliness-on-health-and-strategies-for-recovery/Assets/lonely.jpg
Labels: enhancement, good first issue, gssoc, level3

#399 HIV/AIDS: Understanding and Management converted into French and Spanish
  DataSources/French/HIV-French.md
  DataSources/Spanish/HIV-Spanish.md
Labels: good first issue, gssoc, level2

#404 Articles on OsteoArthritis added
  DataSources/Diet_for_OsteoArthritis/Article_English.md
  DataSources/Diet_for_OsteoArthritis/Article_Hindi.md
Labels: good first issue, gssoc, level3

#413 Added "Pneumonia in Children: Prevention and Care"
  Datasources/Pneumonia in Children Prevention and Care/English.md
  Datasources/Pneumonia in Children Prevention and Care/Hindi.md
Labels: good first issue, gssoc, level3

#421 add article on The Impact of Stress on Physical and Mental Health
  DataSources/English/The Impact of Stress on Physical and Mental Health.md
  DataSources/Hindi/The Impact of Stress on Physical and Mental Health in Hindi.md
Labels: enhancement, good first issue, gssoc, level3

#423 Power of Subconscious Brain.md
  Datasources/Subconscious Brain.md
Labels: enhancement, good first issue, gssoc, level3

#428 Article about Advances in Inmmunotherepy for cancer treatment
  DataSources/English/Immunotherapy-Cancer-Treatment.md
Labels: enhancement, good first issue, gssoc, level3

#397 Added "Nutrition in Different Cultures"
  Datasources/Nutrition in Different Cultures/English.md
  Datasources/Nutrition in Different Cultures/Hindi.md
Labels: enhancement, good first issue, gssoc, level3

#417 Added document on Genetic diseases prevention and maintenance
  DataSources/English/Cluster on Genetic-Diseases.md
Labels: enhancement, good first issue, gssoc, level3

#438 Replace any with proper type, & use NativeStackScreenProps
  frontend/App.tsx
  frontend/index.js
  frontend/package-lock.json
  frontend/src/components/ActivityOverview.tsx
  frontend/src/components/AddIcon.tsx
  frontend/src/components/ArticleCard.tsx
  frontend/src/components/BottomSheetDialog.tsx
  frontend/src/components/CategoriesFlatlistModal.tsx
  frontend/src/components/ContactTab.tsx
  frontend/src/components/EmailInputModal.tsx
  frontend/src/components/FilterModal.tsx
  frontend/src/components/GeneralTab.tsx
  frontend/src/components/HomeScreenHeader.tsx
  frontend/src/components/NoInternet.tsx
  frontend/src/components/ProfessionalTab.tsx
  frontend/src/components/ProfileHeader.tsx
  frontend/src/helper/Utils.ts
  frontend/src/models/User.ts
  frontend/src/navigations/StackNavigation.tsx
  frontend/src/navigations/TabBar.tsx
  frontend/src/navigations/TabNavigation.tsx
  frontend/src/screens/HomeScreen.tsx
  frontend/src/screens/PodcastsScreen.tsx
  frontend/src/screens/ProfileEditScreen.tsx
  frontend/src/screens/ProfileScreen.tsx
  frontend/src/screens/SplashScreen.tsx
  frontend/src/screens/article/ArticleScreen.tsx
  frontend/src/screens/article/EditorScreen.tsx
  frontend/src/screens/article/PreviewScreen.tsx
  frontend/src/screens/auth/LoginScreen.tsx
  frontend/src/screens/auth/NewPasswordScreen.tsx
  frontend/src/screens/auth/OtpScreen.tsx
  frontend/src/screens/auth/SignUpScreenFirst.tsx
  frontend/src/screens/auth/SignUpScreenSecond.tsx
  frontend/src/services/AuthApiService.ts
  frontend/src/type.ts
Labels: enhancement, gssoc, level3

#452 Benefits of Yoga for Mental and Physical Health
  Datasources/Benefits of Yoga for Mental and Physical Health/Article-english.md
  Datasources/Benefits of Yoga for Mental and Physical Health/Article-hindi.md
  Datasources/Benefits of Yoga for Mental and Physical Health/Assets/psycological benefits yoga.jpeg
  Datasources/Benefits of Yoga for Mental and Physical Health/Assets/yog.jpeg
  Datasources/Benefits of Yoga for Mental and Physical Health/Assets/yoga mental health.jpeg
  Datasources/Benefits of Yoga for Mental and Physical Health/Assets/yoga.jpeg
Labels: enhancement, good first issue, gssoc, level3

#434 Added the documentation on Role of AI in Modern Healthcare
  DataSources/English/AI-Modern-healthcare.md
  DataSources/English/Firefly AI in COVID-19 Vaccine Development Image- AI simulations assisting in the rapid development  (1).jpg
  DataSources/English/Firefly AI in Drug Discovery Image- AI analyzing chemical compounds to identify potential drug candi.jpg
  DataSources/English/Firefly AI in Healthcare Administration Image- AI managing administrative tasks like appointment sch.jpg
Labels: enhancement, good first issue, gssoc, level3

#437 Digital Detox: Reconnecting with Life in a Hyper-Connected World ( English, Hindi & Marathi)
  DataSources/English/Digital-Detox.md
  DataSources/Hindi/Digital-Detox-Hindi.md
  DataSources/Marathi/Digital-Detox-Marathi.md
Labels: enhancement, good first issue, gssoc, level3

#443 Added "Kidney Stones and Pregnancy Risks and Management
  Datasources/Kidney Stones and Pregnancy Risks and Management/English.md
  Datasources/Kidney Stones and Pregnancy Risks and Management/Hindi.md
Labels: enhancement, good first issue, gssoc, level3

#446 Added "When to See a Doctor for Swimmer's Ear"
  Datasources/When to See a Doctor for Swimmers Ear/English.md
Labels: enhancement, good first issue, gssoc, level3

#451 Digital Detox: Balancing Technology and Mental Health (Spanish and Malay)
  Datasources/Digital_Detox_Malay.md
  Datasources/Digital_Detox_Spanish.md
Labels: good first issue, gssoc, level2

#455 Added Seasonal Affective Disorder
  Datasources/Understanding and Managing Seasonal Affective Disorder/Article-eng.md
  Datasources/Understanding and Managing Seasonal Affective Disorder/Article-hindi.md
  Datasources/Understanding and Managing Seasonal Affective Disorder/Assets/SAD.jpeg
  Datasources/Understanding and Managing Seasonal Affective Disorder/Assets/SAD2.jpeg
  Datasources/Understanding and Managing Seasonal Affective Disorder/Assets/sAD3.jpeg
Labels: enhancement, gssoc, level3

#463 Nanotechnology in Medicine
  Datasources/Nanotechnology.md
Labels: enhancement, good first issue, gssoc, level3

#464 PCOS (Spanish and Malay)
  Datasources/PCOD_Unplugged_Malay.md
  Datasources/PCOD_Unplugged_Spanish.md
Labels: good first issue, gssoc, level2

#458 Articles on Gene editing added
  DataSources/English/CRISPR-Cas9.md
  DataSources/Hindi/CRISPR-Cas9.md
Labels: enhancement, good first issue, gssoc, level3

#460 Converted articles in french
  DataSources/French/Alzheimers Disease.md
  DataSources/French/Are People Truly Possessed by Ghosts.md
  DataSources/French/Calcium-Deficiency-Diseases.md
  DataSources/French/Cluster Knowledge on Genetic Diseases.md
  DataSources/French/Dehydration.md
  DataSources/French/Effects of music in mental health.md
  DataSources/French/Emotional Intelligence.md
  DataSources/French/Hypertension.md
  DataSources/French/Immunotherapy for Cancer Treatment.md
  DataSources/French/Iron Deficiency Disease.md
  DataSources/French/Mental Health Awareness and Stigma.md
  DataSources/French/Osteoporosis.md
  DataSources/French/Plant-Based Diets.md
  DataSources/French/Robot Assisted Knee Joint Replacement Surgery.md
  DataSources/French/Role of Diet in Managing Autoimmune Diseases.md
  DataSources/French/The Role of Artificial Intelligence (AI) in Modern Healthcare.md
  DataSources/French/Womens Health - Key Issues and Preventative Measures.md
  DataSources/French/digital detox.md
  DataSources/French/exercise and its role in preventing diseases.md
  DataSources/French/genetic disorders and their incidence.md
  DataSources/French/healthy aging.md
  DataSources/French/hyperactivity disorder (ADHD).md
Labels: enhancement, good first issue, gssoc, level3

#462 Articles on Hormal balance added
  DataSources/English/Effect-of-Diet-on-Hormonal-balance.md
  DataSources/Hindi/Effect-of-Diet-on-Hormonal-balance.md
Labels: enhancement, good first issue, gssoc, level3

#467 Article on digestion for mental health
  DataSources/Assets/Firefly Good Digestion of a healthy person 85881.jpg
  DataSources/English/Digestion for mental health.md
Labels: enhancement, good first issue, gssoc, level3

#469 Added article on cervical cancer prevention and HPV Vaccination
  DataSources/Assets/Firefly HPV vaccination 85881.jpg
  DataSources/English/Cervical cancer.md
Labels: enhancement, good first issue, gssoc, level3

#471 Added Create Cystic_Fibrosis
  Datasources/Cystic_Fibrosis.md
Labels: good first issue, gssoc, level3

#472 Menstural cycle and its impact on health
  DataSources/Assets/Firefly well group of girls having good vibes and hormonal well being in a natural environment and h.jpg
  DataSources/English/Menstural health.md
Labels: enhancement, good first issue, gssoc, level3

#473 Hemophilia
  Datasources/Hemophilia.md
Labels: enhancement, good first issue, gssoc, level3

#483 feat: Added Effect of ECT treatment on mental and physical health
  DataSources/Effect of ECT treatment on mental and physical health_English.md
  DataSources/Effect of ECT treatment on mental and physical health_Hindi.md
Labels: enhancement, good first issue, gssoc, level3

#484 Obsessive-Compulsive Disorder
  Datasources/Obsessive-Compulsive Disorder/Article-eng.md
  Datasources/Obsessive-Compulsive Disorder/Article-hindi.md
  Datasources/Obsessive-Compulsive Disorder/Assets/OCD1.png
  Datasources/Obsessive-Compulsive Disorder/Assets/ocd.jpeg
  Datasources/Obsessive-Compulsive Disorder/Assets/ocd3.jpeg
Labels: enhancement, good first issue, gssoc, level3

#485 Understanding Autism Spectrum Disorder (ASD).
  DataSources/English/Autism-Spectrum-Disorder(ASD)-English.md
  DataSources/Hindi/Autism-Spectrum-Disorder(ASD)-Hindi.md
Labels: enhancement, good first issue, gssoc, level3

#490 Added "Osteoporosis Overview Strengthening Bones and Preventing Fractures"
  Datasources/Osteoporosis Overview Strengthening Bones and Preventing Fractures/English.md
Labels: enhancement, good first issue, gssoc, level3

#487 feat: Added Understanding Insomnia: Causes, Symptoms, and Solutions
  DataSources/Understanding Insomnia Causes Symptoms and Solutions_English.md
  DataSources/Understanding Insomnia Causes Symptoms and Solutions_Hindi.md
Labels: enhancement, good first issue, gssoc, level3

#492 Added "Sjögren’s Syndrome Survival Managing Dryness and Fatigue"
  Datasources/Sjögren’s Syndrome Survival Managing Dryness and Fatigue/English.md
Labels: enhancement, good first issue, gssoc, level3

#507 Rheumatoid Arthritis (Spanish and Malay)
  Datasources/Rheumatoid_Arthritis_Malay.md
  Datasources/Rheumatoid_Arthritis_Spanish.md
Labels: enhancement, good first issue, gssoc, level3

#470 Added article on hydration and its affect on overall health
  DataSources/Assets/Firefly water in bottle in a very natural environment peaceful and relaxed 13759.jpg
  DataSources/English/Hydration for health.md
  DataSources/Hindi/Hydration for health.md
Labels: enhancement, good first issue, gssoc, level3

#475 Added Obesity information and Preventions
  Datasources/Obesity.md
Labels: enhancement, good first issue, gssoc, level3

#478 Added Antimicrobial-Resistance preventions
  Antimicrobial-Resistance.md
Labels: enhancement, good first issue, gssoc, level3

#479 Pediatric Health
  DataSources/Fasting.md
  DataSources/Pediatric Health.md
Labels: enhancement, good first issue, gssoc, level3

#468 Added Polio Prevenntion
  Polio-Preventions.md
Labels: enhancement, gssoc, level3

#513 Image & Video Select functionality add in EditorScreen
  frontend/ios/Podfile.lock
  frontend/ios/UltimateHealth/Info.plist
  frontend/package-lock.json
  frontend/package.json
  frontend/src/navigations/StackNavigation.tsx
  frontend/src/screens/article/EditorScreen.tsx
Labels: enhancement, good first issue, gssoc, level2

#491 Added "Arrhythmia Insights Understanding and Managing Irregular Heartbeats"
  Datasources/Arrhythmia Insights Understanding and Managing Irregular Heartbeats/English.md
Labels: enhancement, good first issue, gssoc, level3

#517 Fasting (Hindi and Spanish)
  Datasources/Fasting_Hindi.md
  Datasources/Fasting_Spanish.md
Labels: good first issue, gssoc, level2

#515 Quantum Computing in Drug Discovery Added
  DataSources/English/Quantum-Computing-in-Drug-Discovery.md
Labels: enhancement, good first issue, gssoc, level3

#512 Added Alzheimer’s-Disease
  Datasources/Demantia_vs_Alzeimers_diseases.md
Labels: enhancement, good first issue, gssoc, level3

#518 Artificial Intelligence in Diagnostics Added
  DataSources/English/Artificial Intelligence in Diagnostics.md
Labels: enhancement, good first issue, gssoc, level3

#519 Autism Spectrum Disorder (ASD) Updation
  DataSources/English/Autism Spectrum Disorder.md
  DataSources/English/image.png
Labels: enhancement, good first issue, gssoc, level3

#520 Add Back Button in EditorScreen & PreviewScreen
  frontend/src/helper/Utils.ts
  frontend/src/navigations/StackNavigation.tsx
  frontend/src/screens/ProfileScreen.tsx
  frontend/src/screens/article/EditorScreen.tsx
  frontend/src/screens/article/PreviewScreen.tsx
  frontend/src/type.ts
Labels: enhancement, good first issue, gssoc, level2

#521 Creatinine Levels and Dialysis: When is Treatment Necessary?
  DataSources/English/Creatinine Levels and Dialysis English.md
  DataSources/Hindi/Creatinine Levels and Dialysis Hindi.md
Labels: good first issue, gssoc, level3

#523 Crohn’s Disease Chronicles: Managing Flare-Ups and Maintaining
  DataSources/English/Crohn’s Disease Chronicles English.md
  DataSources/Hindi/Crohn’s Disease Chronicles Hindi.md
Labels: good first issue, gssoc, level3

#525 Added The Benefits of Probiotics for Digestive Health
  DataSources/Added The Benefits of Probiotics for Digestive Health_English.md
  DataSources/Added The Benefits of Probiotics for Digestive Health_Hindi.md
Labels: good first issue, gssoc, level3

#526 Understanding Multiple Sclerosis: Symptoms, Diagnosis, and Treatment
  DataSources/English/Understanding Multiple Sclerosis Hindi.md
  DataSources/Hindi/Understanding Multiple Sclerosis Hindi.md
Labels: enhancement, good first issue, gssoc, level3

#524 Added Oral_diseases_and_prevention.
  Datasources/Oral_diseases_and_prevention.md
Labels: enhancement, good first issue, gssoc, level3

#527 Mental Health and Neuroscience Added
  DataSources/English/Mental Health and Neurosciences.md
Labels: good first issue, gssoc, level3

#529 New article added
  DataSources/English/How-to-Balance-Work.md
  DataSources/Hindi/How-to-balance-work.md
Labels: gssoc, level3

#537 Integrated React Native TTS+
  frontend/ios/Podfile.lock
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/PodcastPlayer.tsx
Labels: enhancement

#542 Added Loader Animation
  frontend/ios/Podfile.lock
  frontend/ios/UltimateHealth.xcodeproj/project.pbxproj
  frontend/ios/UltimateHealth/AppDelegate.h
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/LottieAnimation/LoaderAnimation.json
  frontend/src/assets/LottieAnimation/NetworkAnimation.json
  frontend/src/components/Loader.tsx
  frontend/src/components/NetworkCheck.tsx
Labels: enhancement

#546 Added Dropdown
  frontend/src/components/AddSpecializationModal.tsx
  frontend/src/components/DropDownComponent.tsx
  frontend/src/components/Dropdown.tsx
  frontend/src/screens/auth/LoginScreen.tsx
Labels: enhancement
