Repository SB2318/UltimateHealth, pull requests merged in 2024-07, with the labels that each got.

#148 Added Article - Can a cancer patient live a normal life?
  DataSources/Article.md
  DataSources/Assets/320px-Preventable_Causes_of_Cancer_in_US.png
  DataSources/Assets/Breast-cancer-age-distribution-N-1255-This-graph-shows-age-distribution-of-breast.png
  DataSources/Assets/Components-of-the-tumor-microenvironment.png
  DataSources/Assets/Normal_and_cancer_cells_structure.jpg
  DataSources/Assets/Picture-case-study-melanoma.png
  DataSources/Assets/Rates-of-depression-treatment-by-type-of-cancer-among-adults-with-cancer-and-comorbid.png
Labels: documentation, gssoc, level3

#154 [Feature]: Prepare a Markdown file for the following topics : Emotional Intelligence. #145
  DataSources/Emotional_Intelligence_A_cause_or_Problem.md
Labels: good first issue, gssoc, level3

#159 💡[FEATURE]: Adding Database model for Articles #57
  backend/models/Articles.js
  backend/package-lock.json
  backend/package.json
Labels: good first issue, gssoc, level2

#163 [Docs]: Effects of music in mental health : The Impact of Music on Emotions, Mental Growth, and Meditation #162
  DataSources/Effects of music in mental health.md
Labels: good first issue, gssoc, level3

#165 Article View Page Design
  frontend/Article View.png
Labels: good first issue, gssoc, level2

#168 Added Profile Page
  frontend/ios/Podfile.lock
  frontend/ios/UltimateHealth/Info.plist
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/svg/EllipseSvg.jsx
  frontend/src/components/ActivityOverview.tsx
  frontend/src/components/ProfileHeader.tsx
  frontend/src/navigations/TabNavigation.tsx
  frontend/src/screens/HomeScreen.tsx
  frontend/src/screens/ProfileScreen.tsx
  frontend/src/screens/SplashScreen.tsx
Labels: good first issue, gssoc, level3

#160 💡[Feature]: Article API creation #156
  backend/controllers/articleController.js
  backend/middleware/authentcatetoken.js
  backend/routes/articleRoutes.js
Labels: good first issue, gssoc, level3

#172 Structure the code for HomeScreen
  frontend/src/components/HomeScreenHeader.tsx
  frontend/src/navigations/TabNavigation.tsx
  frontend/src/screens/HomeScreen.tsx
  frontend/src/screens/PodcastsScreen.tsx
  frontend/src/screens/ProfileScreen.tsx
Labels: good first issue, gssoc, level2

#173 Read Article Page
  frontend/src/components/ArticleCard.tsx
  frontend/src/navigations/StackNavigation.tsx
  frontend/src/screens/HomeScreen.tsx
  frontend/src/screens/ProfileScreen.tsx
  frontend/src/screens/article/ArticleScreen.tsx
Labels: good first issue, gssoc, level3

#174 Add action to the call icon and email icon in profile page
  frontend/ios/UltimateHealth/Info.plist
  frontend/src/components/ProfileHeader.tsx
Labels: good first issue, gssoc, level2

#175 Added Profile Api and update profile with article api
  backend/controllers/articleController.js
  backend/controllers/usersControllers.js
  backend/models/UserModel.js
  backend/routes/usersRoutes.js
Labels: enhancement, gssoc, level3

#187 💡[Feature]: Follow and Unfollow functionality from backend. #184
  backend/controllers/usersControllers.js
  backend/routes/usersRoutes.js
Labels: enhancement, gssoc, level3

#188 Translated All English articles to Hindi
  DataSources/Hindi/Article01.md
  DataSources/Hindi/Article10.md
  DataSources/Hindi/Caring for children with disabilities.md
  DataSources/Hindi/Effects of music in mental health.md
  DataSources/Hindi/Emotional_Intelligence_A_cause_or_Problem.md
Labels: enhancement, gssoc, level3

#186 📝[Docs]: Chronic Pain (Long Term) #178
  DataSources/chronic_pain.md
Labels: good first issue, gssoc, level2

#193 Stroke : Signs, Preventation and Recovery
  DataSources/Article02.md
  DataSources/Article03.md
Labels: enhancement, good first issue, gssoc, level3

#196 added Diabetes mellitus vs Diabetes insipidus
  DataSources/Diabetes mellitus vs Diabetes insipidus/Article.md
  DataSources/Diabetes mellitus vs Diabetes insipidus/Assetss/Diabetes_mellitus_vs_diabetes_insipidus.png
  DataSources/Diabetes mellitus vs Diabetes insipidus/Assetss/Diagnose.gif
  DataSources/Diabetes mellitus vs Diabetes insipidus/Assetss/Insipidus.jpeg
  DataSources/Diabetes mellitus vs Diabetes insipidus/Assetss/Symptoms _of_Diabetes _Mellitus.png
  DataSources/Diabetes mellitus vs Diabetes insipidus/Assetss/Symptoms_of_Insipidus _Diabetes.png
  DataSources/Diabetes mellitus vs Diabetes insipidus/Assetss/therapeutic approach to type 2.gif
Labels: good first issue, gssoc, level3

#195 Alzheimer's Diseases: Understanding the Symptoms and Care #181
  DataSources/Alzheimer's Disease.md
  DataSources/Hindi/Alzheimer's Disease.md
Labels: enhancement, gssoc, level3

#201 added copd article
  DataSources/Article04.md
  DataSources/Article05.md
Labels: enhancement, gssoc, level3

#206 [Feature]: Implement User Article Engagement (Read & Write Count of articles) (Backend) #200
  backend/controllers/articleController.js
  backend/controllers/usersControllers.js
  backend/models/UserModel.js
  backend/package-lock.json
  backend/package.json
  backend/routes/usersRoutes.js
Labels: enhancement, gssoc, level3

#204 Calcium deficiency
  DataSources/Calcium-Deficiency-Diseases-English.md
  DataSources/Calcium-Deficiency-Diseases-Hindi.md
Labels: enhancement, gssoc, level2

#214 Added All Articles Conversions in Tamil and Malay
  DataSources/Malay/Alzheimer's Disease.md
  DataSources/Malay/Article01.md
  DataSources/Malay/Article10.md
  DataSources/Malay/Caring for children with disabilities.md
  DataSources/Malay/Effects of music in mental health.md
  DataSources/Malay/Emotional_Intelligence_A_cause_or_Problem.md
  DataSources/Malay/chronic_pain.md
  DataSources/Tamil/Alzheimer's Disease.md
  DataSources/Tamil/Article.md
  DataSources/Tamil/Article01.md
  DataSources/Tamil/Article10.md
  DataSources/Tamil/Caring for children with disabilities.md
  DataSources/Tamil/Effects of music in mental health.md
  DataSources/Tamil/Emotional_Intelligence_A_cause_or_Problem.md
  DataSources/Tamil/chronic_pain.md
Labels: enhancement, gssoc, level3

#215 Iron Deficiency Disease Docs
  DataSources/Article06.md
  DataSources/Article07.md
  package-lock.json
Labels: enhancement, gssoc, level3

#217 Make Categories Dynamic In the Home Page .(Integrate Tag API)
  frontend/package-lock.json
  frontend/src/helper/APIUtils.ts
  frontend/src/helper/Utils.ts
  frontend/src/screens/HomeScreen.tsx
  frontend/src/type.ts
Labels: enhancement, gssoc, level3

#219 Vitamin D Deficinecy disease added
  DataSources/Vitamin-D-Deficiency-Diseases-English.md
  DataSources/Vitamin-D-Deficiency-Diseases-Hindi.md
Labels: enhancement, gssoc, level3

#218 Fixed #216
  DataSources/Caring for children with disabilities-hindi.md
  DataSources/Caring-for-children-with-disabilities-tamil.md
Labels: good first issue, gssoc, level3

#225 Spanish 6 Article
  DataSources/Spanish/Alzheimer's-Disease-Spanish.md
  DataSources/Spanish/Calcium-Deficiency-Diseases-Spanish.md
  DataSources/Spanish/Caring for children with disabilities Spanish.md
  DataSources/Spanish/Emotional_Intelligence_A_cause_or_Problem_Spanish.md
  DataSources/Spanish/Iron-Deficiency-Diseases-Spanish.md
  DataSources/Spanish/copd Spanish.md
Labels: good first issue, gssoc, level2

#227 Seven Article converted into Spanish
  DataSources/English/Vitamin-D-Deficiency-Diseases-English.md
  DataSources/Spanish/Effects of music in mental health Spanish.md
  DataSources/Spanish/Storke_Signs_Preventation_Recovery_Spanish.md
  DataSources/Spanish/Vitamin-D-Deficiency-Diseases-English-Spanish.md
  DataSources/Spanish/Worst_Epidemic_In_india_Spanish.md
  DataSources/Spanish/can_a_cancer_patient_live_normal_life-Spanish.md
  DataSources/Spanish/chronic_pain_Spanish.md
  DataSources/Spanish/diabetes_melitus_insipidus.md
Labels: good first issue, gssoc, level2

#191 [Docs]: Robot Assisted Knee Joint Replacement Surgery
  DataSources/Article08.md
Labels: good first issue, gssoc, level3

#233 Added Tranlation of Left Articles
  DataSources/Hindi/diabetes_melitus_insipidus.md
  DataSources/Malay/Calcium-Deficiency-Diseases-Malay.md
  DataSources/Malay/Iron_Deficiency.md
  DataSources/Malay/Storke_Signs_Preventation_Recovery.md
  DataSources/Malay/Vitamin-D-Deficiency-Diseases.md
  DataSources/Malay/copd.md
  DataSources/Malay/diabetes_melitus_insipidus.md
  DataSources/Tamil/Calcium-Deficiency-Diseases.md
  DataSources/Tamil/Iron_Deficiency.md
  DataSources/Tamil/Storke_Signs_Preventation_Recovery.md
  DataSources/Tamil/Vitamin-D-Deficiency-Diseases.md
  DataSources/Tamil/copd.md
  DataSources/Tamil/diabetes_melitus_insipidus.md
Labels: good first issue, gssoc, level3

#235 Profile API integration
  backend/routes/usersRoutes.js
  frontend/src/components/ProfileHeader.tsx
  frontend/src/helper/APIUtils.ts
  frontend/src/screens/ProfileScreen.tsx
  frontend/src/type.ts
Labels: enhancement, gssoc, level3

#236 Vitamin d and Iron Docs converted into Marathi
  DataSources/Marathi/Iron_Deficiency_Marathi.md
  DataSources/Marathi/Vitamin-D-Deficiency-Diseases-Marathi.md
Labels: good first issue, gssoc, level2

#237 About Healthy Aging
  DataSources/Health-aging.md
Labels: good first issue, gssoc, level3

#238 Understanding and Managing Chronic Illness
  DataSources/chronic-illness.md
Labels: good first issue, gssoc, level3

#244 Fixes #232
  DataSources/Exercise and Its Role in Preventing Diseases.md
Labels: good first issue, gssoc, level3

#245 Iodine deficiency docs converted successfully
  DataSources/English/Iodine_Deficiency_Disease_English.md
  DataSources/Hindi/Iodine_Deficiency_Disease_Hindi.md
  DataSources/Malay/Iodine_Deficiency_Disease_malay.md
  DataSources/Marathi/Iodine_Deficiency_Disease_Marathi.md
  DataSources/Spanish/Iodine_Deficiency_Disease_Spanish.md
  DataSources/Tamil/Iodine_Deficiency_Disease_Tamil.md
Labels: enhancement, gssoc, level3

#247 The Impact of Air Quality on Health
  DataSources/The Impact of Air Quality on Health.md
Labels: good first issue, gssoc, level3

#248 How to Prevent and Treat Osteoporosis
  DataSources/Osteoporosis.md
Labels: good first issue, gssoc, level3

#253 Role of Diet in Managing Autoimmune Diseases
  DataSources/Role of Diet.md
Labels: good first issue, gssoc, level3

#255 Dehydration
  DataSources/Dehydration/Article-English.md
  DataSources/Dehydration/Article-Hindi.md
  DataSources/Dehydration/Assets/Dehydration.jpeg
  DataSources/Dehydration/Assets/Dehydration_hindi.jpeg
  DataSources/Dehydration/Assets/Percentages.jpg
  DataSources/Dehydration/Assets/stages_dehydration.jpeg
  DataSources/Dehydration/Assets/sun.jpeg
  DataSources/Diabetes mellitus vs Diabetes insipidus/Article.md
Labels: good first issue, gssoc, level3

#256 Converted into marathi
  DataSources/Marathi/Alzheimer's Disease Marathi.md
  DataSources/Marathi/Calcium-Deficiency-Diseases-English-Marathi.md
  DataSources/Marathi/Caring for children with disabilities Marathi.md
  DataSources/Marathi/Effects of music in mental health Marathi.md
  DataSources/Marathi/Emotional_Intelligence_A_cause_or_Problem_Marathi.md
  DataSources/Marathi/Storke_Signs_Preventation_Recovery_Marathi.md
  DataSources/Marathi/Worst_Epidemic_In_india_marathi.md
  DataSources/Marathi/can_a_cancer_patient_live_normal_life_marathi.md
  DataSources/Marathi/chronic_pain_marathi.md
  DataSources/Marathi/copd-Marathi.md
  DataSources/Marathi/diabetes_melitus_insipidus_marathi.md
Labels: good first issue, gssoc, level3

#263 EditProfile frontend implementation
  frontend/src/components/ContactTab.tsx
  frontend/src/components/GeneralTab.tsx
  frontend/src/components/PasswordTab.tsx
  frontend/src/components/ProfessionalTab.tsx
  frontend/src/components/ProfileHeader.tsx
  frontend/src/navigations/StackNavigation.tsx
  frontend/src/screens/ProfileEditScreen.tsx
Labels: enhancement, gssoc, level3

#264 Addition and Updating of Links in README.md and Learn.md files
  Learn.md
  README.md
Labels: good first issue, gssoc, level1

#221 Hypertension Docs Added
  DataSources/Hypertension-the-silent-killer-english.md
  DataSources/Hypertension-the-silent-killer-hindi.md
Labels: good first issue, gssoc, level3

#283 Adding Installation and Setup Guide
  README.md
Labels: good first issue, gssoc, level1

#284 Podcast Screen Implementation Frontend
  frontend/ios/Podfile.lock
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/PodcastCard.tsx
  frontend/src/components/PodcastPlayer.tsx
  frontend/src/helper/Utils.ts
  frontend/src/navigations/TabNavigation.tsx
  frontend/src/screens/PodcastsScreen.tsx
  frontend/src/type.ts
Labels: good first issue, gssoc, level3
