Repository SB2318/UltimateHealth, pull requests merged in 2024-05, with the labels that each got.

#25 Added the new code of conduct
  CODE_OF_CONDUCT.md
Labels: documentation, gsssoc'24, level1

#16 Create LICENSE
  LICENSE
Labels: gsssoc'24, level1

#35 [Feat]: add issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/docs.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement, good first issue, gssoc'24, level1

#43 Create pull_request.md
  .github/ISSUE_TEMPLATE/pull_request.md
Labels: enhancement, gssoc, level1

#41 Added CONTRIBUTING.md
  CONTRIBUTING.md
Labels: good first issue, gssoc, level1

#46 Implement Bottom Tab Navigation In Mobile App
  frontend/App.tsx
  frontend/android/app/build.gradle
  frontend/android/build.gradle
  frontend/android/gradlew
  frontend/babel.config.js
  frontend/ios/Podfile.lock
  frontend/ios/UltimateHealth.xcodeproj/project.pbxproj
  frontend/ios/UltimateHealth.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  frontend/ios/UltimateHealth/Info.plist
  frontend/package-lock.json
  frontend/package.json
  frontend/react-native.config.js
  frontend/src/navigations/TabBar.tsx
  frontend/src/navigations/TabNavigation.tsx
  frontend/src/screens/HomeScreen.tsx
  frontend/src/screens/PodcastsScreen.jsx
  frontend/src/screens/ProfileScreen.jsx
Labels: enhancement, good first issue, gssoc, level2

#52 Added contributors list
  README.md
Labels: good first issue, gssoc24, level1

#53 Login Signup Functionality Implemented
  backend/.env
  backend/.gitignore
  backend/config/database.js
  backend/controllers/usersControllers.js
  backend/models/UserModel.js
  backend/models/usersModel.js
  backend/package-lock.json
  backend/package.json
  backend/routes/index.js
  backend/routes/usersRoutes.js
  backend/server.js
  backend/ultimate_health_backend/package-lock.json
  backend/ultimate_health_backend/package.json
  backend/ultimate_health_backend/server.js
Labels: enhancement, gssoc24, backend-task, level3

#54 Middleware and Protected Routes Implemented
  backend/auth/authMiddleware.js
  backend/controllers/usersControllers.js
  backend/package-lock.json
  backend/package.json
  backend/routes/usersRoutes.js
  backend/server.js
Labels: enhancement, gssoc24, level2, backend-task

#58 Design a SplashScreen and Integrate it with the project (Implement Stack Navigation) #30
  frontend/src/navigations/StackNavigation.js
  frontend/src/screens/SplashScreen.jsx
Labels: enhancement, gssoc24, level2

#64 Design Login Screen
  frontend/App.tsx
  frontend/src/helper/Metric.ts
  frontend/src/screens/HomeScreen.tsx
  frontend/src/screens/auth/LoginScreen.tsx
Labels: good first issue, gssoc24, level2, design

#71 added the workflow as mentioned in issue #68
  .github/workflows/close-on-merge.yml
Labels: enhancement, gssoc24, level2

#74 added remaining workflows
  .github/workflows/autocomment-iss-close.yml
  .github/workflows/close-on-merge.yml
Labels: good first issue, gssoc24, level2

#75 Changed location of pull request template to fix bug
  .github/pull_request_template.md
Labels: good first issue, gssoc, level1

#59 Readme.md set for the Backend Setup
  README.md
  backend/README.md
Labels: enhancement, gssoc, level1

#78 Applying Fonts to Text in React Native
  frontend/App.tsx
  frontend/android/app/src/main/assets/fonts/Lobster-Regular.ttf
  frontend/android/link-assets-manifest.json
  frontend/ios/Podfile.lock
  frontend/ios/UltimateHealth.xcodeproj/project.pbxproj
  frontend/ios/UltimateHealth/Info.plist
  frontend/ios/link-assets-manifest.json
  frontend/package-lock.json
  frontend/package.json
  frontend/react-native.config.js
  frontend/src/assets/fonts/Lobster-Regular.ttf
  frontend/src/screens/SplashScreen.jsx
  frontend/src/screens/auth/LoginScreen.tsx
Labels: good first issue, gssoc, level2

#81 Update README.md
  README.md
Labels: good first issue, gssoc, level1

#83 Added learn.md
  Learn.md
Labels: good first issue, gssoc, level1

#93 Added Restriction For Navigation Between SplashScreen and LoginScreen #63
  README.md
  backend/package-lock.json
  backend/package.json
  frontend/App.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/src/navigations/StackNavigation.js
  frontend/src/screens/SplashScreen.jsx
  frontend/src/screens/StorageUtils.jsx
  frontend/src/screens/auth/LoginScreen.tsx
Labels: enhancement, gssoc, level2

#91 [FEATURE]: : Implementing Forgot Password Functionality with Email OTP Fixed
  backend/.env
  backend/controllers/usersControllers.js
  backend/models/UserModel.js
  backend/package-lock.json
  backend/package.json
  backend/routes/usersRoutes.js
Labels: enhancement, gssoc, level3
